### ISSUE TITLE
Isolate user code and an example

### ISSUE THREAD

**Issue by p-jean** [a3f/mitm0#4]
Hi,

Suggested changes
[mitm.c.txt](https://github.com/a3f/mitm0/files/1972623/mitm.c.txt)

1) Created minimal mitm_from_slave() and mitm_from_master() functions to isolate user code.
2) Added a simple example: intercept ping

..PJ

**Comment by a3f** [comment]
Thanks! I created a pull request (#5) out of your modified source file. Lets continue our discussion there.

**Comment by a3f** [comment]
Merged with minor modifications. Only issue I fixed was 64-bit support (Whether `skb->tail` is a pointer depends on `NET_SKBUFF_DATA_USES_OFFSET`, which itself depends on whether pointers are 32 or 64 bits). Thanks again!
